version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./services/api-gateway
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - CORE_API_URL=http://core:4000
      - AUTH_SERVICE_URL=http://auth:4001
      - CHAT_SERVICE_URL=http://chat:4002
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - core
      - auth
      - chat
    networks:
      - wellio-network

  # Core API Service
  core:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wellio_core
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - CORS_ORIGIN=http://localhost:5173
      - AI_SERVICE_URL=http://ai:8001
      - CHAT_SERVICE_URL=http://chat:4002
      - AUTH_SERVICE_URL=http://auth:4001
      - WORKER_URL=http://worker:7000
    depends_on:
      - postgres
      - redis
    networks:
      - wellio-network

  # Auth Service
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=development
      - PORT=4001
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wellio_auth
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    depends_on:
      - postgres
      - redis
    networks:
      - wellio-network

  # Chat Service
  chat:
    build:
      context: ./services/chat
      dockerfile: Dockerfile
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=development
      - PORT=4002
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    networks:
      - wellio-network

  # AI Service
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    environment:
      - NODE_ENV=development
      - PORT=8001
    networks:
      - wellio-network

  # Worker Service
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    environment:
      - NODE_ENV=development
      - PORT=7000
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/wellio_core
    depends_on:
      - redis
      - postgres
    networks:
      - wellio-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wellio_auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/auth/src/config/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./core/schema.sql:/docker-entrypoint-initdb.d/02-core-schema.sql
    networks:
      - wellio-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wellio-network

volumes:
  postgres_data:
  redis_data:

networks:
  wellio-network:
    driver: bridge 