/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateSession
 */
export interface CreateSession {
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    service: string;
    /**
     * 
     * @type {Date}
     * @memberof CreateSession
     */
    startAt: Date;
    /**
     * 
     * @type {number}
     * @memberof CreateSession
     */
    durationMin: number;
    /**
     * 
     * @type {string}
     * @memberof CreateSession
     */
    status?: CreateSessionStatusEnum;
}


/**
 * @export
 */
export const CreateSessionStatusEnum = {
    Scheduled: 'scheduled',
    Completed: 'completed',
    Canceled: 'canceled'
} as const;
export type CreateSessionStatusEnum = typeof CreateSessionStatusEnum[keyof typeof CreateSessionStatusEnum];


/**
 * Check if a given object implements the CreateSession interface.
 */
export function instanceOfCreateSession(value: object): value is CreateSession {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('startAt' in value) || value['startAt'] === undefined) return false;
    if (!('durationMin' in value) || value['durationMin'] === undefined) return false;
    return true;
}

export function CreateSessionFromJSON(json: any): CreateSession {
    return CreateSessionFromJSONTyped(json, false);
}

export function CreateSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateSession {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'service': json['service'],
        'startAt': (new Date(json['start_at'])),
        'durationMin': json['duration_min'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function CreateSessionToJSON(json: any): CreateSession {
    return CreateSessionToJSONTyped(json, false);
}

export function CreateSessionToJSONTyped(value?: CreateSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'service': value['service'],
        'start_at': ((value['startAt']).toISOString()),
        'duration_min': value['durationMin'],
        'status': value['status'],
    };
}

