/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateClient
 */
export interface CreateClient {
    /**
     * 
     * @type {string}
     * @memberof CreateClient
     */
    fullName: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClient
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof CreateClient
     */
    phone?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CreateClient
     */
    services?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CreateClient
     */
    attentionStatus?: CreateClientAttentionStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof CreateClient
     */
    tags?: object;
}


/**
 * @export
 */
export const CreateClientAttentionStatusEnum = {
    OnTrack: 'on_track',
    NeedsAttention: 'needs_attention'
} as const;
export type CreateClientAttentionStatusEnum = typeof CreateClientAttentionStatusEnum[keyof typeof CreateClientAttentionStatusEnum];


/**
 * Check if a given object implements the CreateClient interface.
 */
export function instanceOfCreateClient(value: object): value is CreateClient {
    if (!('fullName' in value) || value['fullName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function CreateClientFromJSON(json: any): CreateClient {
    return CreateClientFromJSONTyped(json, false);
}

export function CreateClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateClient {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['full_name'],
        'email': json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'services': json['services'] == null ? undefined : json['services'],
        'attentionStatus': json['attention_status'] == null ? undefined : json['attention_status'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function CreateClientToJSON(json: any): CreateClient {
    return CreateClientToJSONTyped(json, false);
}

export function CreateClientToJSONTyped(value?: CreateClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full_name': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'services': value['services'],
        'attention_status': value['attentionStatus'],
        'tags': value['tags'],
    };
}

