/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataImport
 */
export interface DataImport {
    /**
     * 
     * @type {string}
     * @memberof DataImport
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof DataImport
     */
    type: DataImportTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof DataImport
     */
    fileId: string;
}


/**
 * @export
 */
export const DataImportTypeEnum = {
    Manual: 'manual',
    Mfp: 'mfp',
    Fatsecret: 'fatsecret'
} as const;
export type DataImportTypeEnum = typeof DataImportTypeEnum[keyof typeof DataImportTypeEnum];


/**
 * Check if a given object implements the DataImport interface.
 */
export function instanceOfDataImport(value: object): value is DataImport {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('fileId' in value) || value['fileId'] === undefined) return false;
    return true;
}

export function DataImportFromJSON(json: any): DataImport {
    return DataImportFromJSONTyped(json, false);
}

export function DataImportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataImport {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'type': json['type'],
        'fileId': json['file_id'],
    };
}

export function DataImportToJSON(json: any): DataImport {
    return DataImportToJSONTyped(json, false);
}

export function DataImportToJSONTyped(value?: DataImport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'type': value['type'],
        'file_id': value['fileId'],
    };
}

