/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HomeSummary
 */
export interface HomeSummary {
    /**
     * 
     * @type {number}
     * @memberof HomeSummary
     */
    totalClients?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeSummary
     */
    activeSessions?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeSummary
     */
    unreadMessages?: number;
    /**
     * 
     * @type {number}
     * @memberof HomeSummary
     */
    pendingTasks?: number;
}

/**
 * Check if a given object implements the HomeSummary interface.
 */
export function instanceOfHomeSummary(value: object): value is HomeSummary {
    return true;
}

export function HomeSummaryFromJSON(json: any): HomeSummary {
    return HomeSummaryFromJSONTyped(json, false);
}

export function HomeSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): HomeSummary {
    if (json == null) {
        return json;
    }
    return {
        
        'totalClients': json['total_clients'] == null ? undefined : json['total_clients'],
        'activeSessions': json['active_sessions'] == null ? undefined : json['active_sessions'],
        'unreadMessages': json['unread_messages'] == null ? undefined : json['unread_messages'],
        'pendingTasks': json['pending_tasks'] == null ? undefined : json['pending_tasks'],
    };
}

export function HomeSummaryToJSON(json: any): HomeSummary {
    return HomeSummaryToJSONTyped(json, false);
}

export function HomeSummaryToJSONTyped(value?: HomeSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'total_clients': value['totalClients'],
        'active_sessions': value['activeSessions'],
        'unread_messages': value['unreadMessages'],
        'pending_tasks': value['pendingTasks'],
    };
}

