/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Insight
 */
export interface Insight {
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Insight
     */
    type?: InsightTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof Insight
     */
    payload?: object;
    /**
     * 
     * @type {Date}
     * @memberof Insight
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const InsightTypeEnum = {
    RetentionOpportunity: 'retention_opportunity',
    ProgressTrend: 'progress_trend',
    ClientInsight: 'client_insight'
} as const;
export type InsightTypeEnum = typeof InsightTypeEnum[keyof typeof InsightTypeEnum];


/**
 * Check if a given object implements the Insight interface.
 */
export function instanceOfInsight(value: object): value is Insight {
    return true;
}

export function InsightFromJSON(json: any): Insight {
    return InsightFromJSONTyped(json, false);
}

export function InsightFromJSONTyped(json: any, ignoreDiscriminator: boolean): Insight {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : json['type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function InsightToJSON(json: any): Insight {
    return InsightToJSONTyped(json, false);
}

export function InsightToJSONTyped(value?: Insight | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'type': value['type'],
        'payload': value['payload'],
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

