/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IntegrationConnect
 */
export interface IntegrationConnect {
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnect
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnect
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof IntegrationConnect
     */
    refreshToken?: string;
}

/**
 * Check if a given object implements the IntegrationConnect interface.
 */
export function instanceOfIntegrationConnect(value: object): value is IntegrationConnect {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    return true;
}

export function IntegrationConnectFromJSON(json: any): IntegrationConnect {
    return IntegrationConnectFromJSONTyped(json, false);
}

export function IntegrationConnectFromJSONTyped(json: any, ignoreDiscriminator: boolean): IntegrationConnect {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'accessToken': json['access_token'],
        'refreshToken': json['refresh_token'] == null ? undefined : json['refresh_token'],
    };
}

export function IntegrationConnectToJSON(json: any): IntegrationConnect {
    return IntegrationConnectToJSONTyped(json, false);
}

export function IntegrationConnectToJSONTyped(value?: IntegrationConnect | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'access_token': value['accessToken'],
        'refresh_token': value['refreshToken'],
    };
}

