/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof Notification
     */
    type?: NotificationTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof Notification
     */
    payload?: object;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    readAt?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof Notification
     */
    createdAt?: Date;
}


/**
 * @export
 */
export const NotificationTypeEnum = {
    Message: 'message',
    Session: 'session',
    Reminder: 'reminder',
    Insight: 'insight',
    System: 'system'
} as const;
export type NotificationTypeEnum = typeof NotificationTypeEnum[keyof typeof NotificationTypeEnum];


/**
 * Check if a given object implements the Notification interface.
 */
export function instanceOfNotification(value: object): value is Notification {
    return true;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'userId': json['user_id'] == null ? undefined : json['user_id'],
        'type': json['type'] == null ? undefined : json['type'],
        'payload': json['payload'] == null ? undefined : json['payload'],
        'readAt': json['read_at'] == null ? undefined : (new Date(json['read_at'])),
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
    };
}

export function NotificationToJSON(json: any): Notification {
    return NotificationToJSONTyped(json, false);
}

export function NotificationToJSONTyped(value?: Notification | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'user_id': value['userId'],
        'type': value['type'],
        'payload': value['payload'],
        'read_at': value['readAt'] === null ? null : ((value['readAt'] as any)?.toISOString()),
        'created_at': value['createdAt'] == null ? undefined : ((value['createdAt']).toISOString()),
    };
}

