/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PaginatedResponsePagination
 */
export interface PaginatedResponsePagination {
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponsePagination
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponsePagination
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponsePagination
     */
    total?: number;
    /**
     * 
     * @type {number}
     * @memberof PaginatedResponsePagination
     */
    totalPages?: number;
    /**
     * 
     * @type {boolean}
     * @memberof PaginatedResponsePagination
     */
    hasNext?: boolean;
}

/**
 * Check if a given object implements the PaginatedResponsePagination interface.
 */
export function instanceOfPaginatedResponsePagination(value: object): value is PaginatedResponsePagination {
    return true;
}

export function PaginatedResponsePaginationFromJSON(json: any): PaginatedResponsePagination {
    return PaginatedResponsePaginationFromJSONTyped(json, false);
}

export function PaginatedResponsePaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponsePagination {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['page_size'] == null ? undefined : json['page_size'],
        'total': json['total'] == null ? undefined : json['total'],
        'totalPages': json['total_pages'] == null ? undefined : json['total_pages'],
        'hasNext': json['has_next'] == null ? undefined : json['has_next'],
    };
}

export function PaginatedResponsePaginationToJSON(json: any): PaginatedResponsePagination {
    return PaginatedResponsePaginationToJSONTyped(json, false);
}

export function PaginatedResponsePaginationToJSONTyped(value?: PaginatedResponsePagination | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'page': value['page'],
        'page_size': value['pageSize'],
        'total': value['total'],
        'total_pages': value['totalPages'],
        'has_next': value['hasNext'],
    };
}

