/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaginatedResponsePagination } from './PaginatedResponsePagination';
import {
    PaginatedResponsePaginationFromJSON,
    PaginatedResponsePaginationFromJSONTyped,
    PaginatedResponsePaginationToJSON,
    PaginatedResponsePaginationToJSONTyped,
} from './PaginatedResponsePagination';

/**
 * 
 * @export
 * @interface PaginatedResponse
 */
export interface PaginatedResponse {
    /**
     * 
     * @type {Array<string>}
     * @memberof PaginatedResponse
     */
    data?: Array<string>;
    /**
     * 
     * @type {PaginatedResponsePagination}
     * @memberof PaginatedResponse
     */
    pagination?: PaginatedResponsePagination;
}

/**
 * Check if a given object implements the PaginatedResponse interface.
 */
export function instanceOfPaginatedResponse(value: object): value is PaginatedResponse {
    return true;
}

export function PaginatedResponseFromJSON(json: any): PaginatedResponse {
    return PaginatedResponseFromJSONTyped(json, false);
}

export function PaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
        'pagination': json['pagination'] == null ? undefined : PaginatedResponsePaginationFromJSON(json['pagination']),
    };
}

export function PaginatedResponseToJSON(json: any): PaginatedResponse {
    return PaginatedResponseToJSONTyped(json, false);
}

export function PaginatedResponseToJSONTyped(value?: PaginatedResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'pagination': PaginatedResponsePaginationToJSON(value['pagination']),
    };
}

