/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionnaireSend
 */
export interface QuestionnaireSend {
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireSend
     */
    clientId: string;
    /**
     * 
     * @type {string}
     * @memberof QuestionnaireSend
     */
    questionnaireId: string;
}

/**
 * Check if a given object implements the QuestionnaireSend interface.
 */
export function instanceOfQuestionnaireSend(value: object): value is QuestionnaireSend {
    if (!('clientId' in value) || value['clientId'] === undefined) return false;
    if (!('questionnaireId' in value) || value['questionnaireId'] === undefined) return false;
    return true;
}

export function QuestionnaireSendFromJSON(json: any): QuestionnaireSend {
    return QuestionnaireSendFromJSONTyped(json, false);
}

export function QuestionnaireSendFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionnaireSend {
    if (json == null) {
        return json;
    }
    return {
        
        'clientId': json['client_id'],
        'questionnaireId': json['questionnaire_id'],
    };
}

export function QuestionnaireSendToJSON(json: any): QuestionnaireSend {
    return QuestionnaireSendToJSONTyped(json, false);
}

export function QuestionnaireSendToJSONTyped(value?: QuestionnaireSend | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'client_id': value['clientId'],
        'questionnaire_id': value['questionnaireId'],
    };
}

