/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Session
 */
export interface Session {
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    clientId?: string;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    service?: string;
    /**
     * 
     * @type {Date}
     * @memberof Session
     */
    startAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof Session
     */
    durationMin?: number;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    status?: SessionStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Session
     */
    joinUrl?: string | null;
}


/**
 * @export
 */
export const SessionStatusEnum = {
    Scheduled: 'scheduled',
    Completed: 'completed',
    Canceled: 'canceled'
} as const;
export type SessionStatusEnum = typeof SessionStatusEnum[keyof typeof SessionStatusEnum];


/**
 * Check if a given object implements the Session interface.
 */
export function instanceOfSession(value: object): value is Session {
    return true;
}

export function SessionFromJSON(json: any): Session {
    return SessionFromJSONTyped(json, false);
}

export function SessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Session {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'clientId': json['client_id'] == null ? undefined : json['client_id'],
        'service': json['service'] == null ? undefined : json['service'],
        'startAt': json['start_at'] == null ? undefined : (new Date(json['start_at'])),
        'durationMin': json['duration_min'] == null ? undefined : json['duration_min'],
        'status': json['status'] == null ? undefined : json['status'],
        'joinUrl': json['join_url'] == null ? undefined : json['join_url'],
    };
}

export function SessionToJSON(json: any): Session {
    return SessionToJSONTyped(json, false);
}

export function SessionToJSONTyped(value?: Session | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'client_id': value['clientId'],
        'service': value['service'],
        'start_at': value['startAt'] == null ? undefined : ((value['startAt']).toISOString()),
        'duration_min': value['durationMin'],
        'status': value['status'],
        'join_url': value['joinUrl'],
    };
}

