/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateClient
 */
export interface UpdateClient {
    /**
     * 
     * @type {string}
     * @memberof UpdateClient
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateClient
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateClient
     */
    phone?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateClient
     */
    services?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof UpdateClient
     */
    attentionStatus?: UpdateClientAttentionStatusEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateClient
     */
    tags?: object;
}


/**
 * @export
 */
export const UpdateClientAttentionStatusEnum = {
    OnTrack: 'on_track',
    NeedsAttention: 'needs_attention'
} as const;
export type UpdateClientAttentionStatusEnum = typeof UpdateClientAttentionStatusEnum[keyof typeof UpdateClientAttentionStatusEnum];


/**
 * Check if a given object implements the UpdateClient interface.
 */
export function instanceOfUpdateClient(value: object): value is UpdateClient {
    return true;
}

export function UpdateClientFromJSON(json: any): UpdateClient {
    return UpdateClientFromJSONTyped(json, false);
}

export function UpdateClientFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateClient {
    if (json == null) {
        return json;
    }
    return {
        
        'fullName': json['full_name'] == null ? undefined : json['full_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'services': json['services'] == null ? undefined : json['services'],
        'attentionStatus': json['attention_status'] == null ? undefined : json['attention_status'],
        'tags': json['tags'] == null ? undefined : json['tags'],
    };
}

export function UpdateClientToJSON(json: any): UpdateClient {
    return UpdateClientToJSONTyped(json, false);
}

export function UpdateClientToJSONTyped(value?: UpdateClient | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'full_name': value['fullName'],
        'email': value['email'],
        'phone': value['phone'],
        'services': value['services'],
        'attention_status': value['attentionStatus'],
        'tags': value['tags'],
    };
}

