/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateSession
 */
export interface UpdateSession {
    /**
     * 
     * @type {string}
     * @memberof UpdateSession
     */
    service?: string;
    /**
     * 
     * @type {Date}
     * @memberof UpdateSession
     */
    startAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof UpdateSession
     */
    durationMin?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateSession
     */
    status?: UpdateSessionStatusEnum;
}


/**
 * @export
 */
export const UpdateSessionStatusEnum = {
    Scheduled: 'scheduled',
    Completed: 'completed',
    Canceled: 'canceled'
} as const;
export type UpdateSessionStatusEnum = typeof UpdateSessionStatusEnum[keyof typeof UpdateSessionStatusEnum];


/**
 * Check if a given object implements the UpdateSession interface.
 */
export function instanceOfUpdateSession(value: object): value is UpdateSession {
    return true;
}

export function UpdateSessionFromJSON(json: any): UpdateSession {
    return UpdateSessionFromJSONTyped(json, false);
}

export function UpdateSessionFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateSession {
    if (json == null) {
        return json;
    }
    return {
        
        'service': json['service'] == null ? undefined : json['service'],
        'startAt': json['start_at'] == null ? undefined : (new Date(json['start_at'])),
        'durationMin': json['duration_min'] == null ? undefined : json['duration_min'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function UpdateSessionToJSON(json: any): UpdateSession {
    return UpdateSessionToJSONTyped(json, false);
}

export function UpdateSessionToJSONTyped(value?: UpdateSession | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'service': value['service'],
        'start_at': value['startAt'] == null ? undefined : ((value['startAt']).toISOString()),
        'duration_min': value['durationMin'],
        'status': value['status'],
    };
}

