/* tslint:disable */
/* eslint-disable */
/**
 * Wellio Core API
 * Core API for the Wellio wellness coaching platform
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: api@wellio.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UploadResponse
 */
export interface UploadResponse {
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    fileId?: string;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    filename?: string;
    /**
     * 
     * @type {number}
     * @memberof UploadResponse
     */
    size?: number;
    /**
     * 
     * @type {string}
     * @memberof UploadResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the UploadResponse interface.
 */
export function instanceOfUploadResponse(value: object): value is UploadResponse {
    return true;
}

export function UploadResponseFromJSON(json: any): UploadResponse {
    return UploadResponseFromJSONTyped(json, false);
}

export function UploadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UploadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'fileId': json['file_id'] == null ? undefined : json['file_id'],
        'filename': json['filename'] == null ? undefined : json['filename'],
        'size': json['size'] == null ? undefined : json['size'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function UploadResponseToJSON(json: any): UploadResponse {
    return UploadResponseToJSONTyped(json, false);
}

export function UploadResponseToJSONTyped(value?: UploadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'file_id': value['fileId'],
        'filename': value['filename'],
        'size': value['size'],
        'url': value['url'],
    };
}

